export const surpriseMePrompts = [
  'un sillón en forma de aguacate',
  'una pintura al óleo surrealista de ensueño de Salvador Dalí de un gato jugando a las damas',
  'osos de peluche comprando comestibles en Japón, ukiyo-e',
  'una pintura al óleo de Matisse de un robot humanoide jugando al ajedrez',
  'panda científico loco mezclando productos químicos brillantes, arte digital',
  'una fotografía macro de 35 mm de dos ratones en Hawái, cada uno de ellos lleva diminutos trajes de baño y lleva diminutas tablas de surf, arte digital',
  'Representación 3D de un lindo pez tropical en un acuario sobre un fondo azul oscuro, arte digital',
  'un astronauta descansando en un resort tropical en el espacio, vaporwave',
  'un retrato de pintura al óleo de un carpincho con túnicas reales medievales y una corona ornamentada sobre un fondo oscuro',
  'una vidriera que representa una hamburguesa y papas fritas',
  'un dibujo a lápiz y acuarela de una ciudad brillante en el futuro con autos voladores',
  'una sala de estar interior iluminada por el sol con una piscina con agua clara y otra piscina con agua translúcida de color rosa pastel, junto a una gran ventana, arte digital',
  'un shiba inu adivino que lee tu destino en una hamburguesa gigante, arte digital',
  '"una nutria marina con un pendiente de perla" de Johannes Vermeer',
  'un dibujo al pastel de un gato molesto en una nave espacial',
  'una pintura de un zorro al estilo de La noche estrellada',
  'un plato de sopa que parece un monstruo, tejido con lana',
  'Un robot de peluche sentado contra una pared amarilla',
  'Una puesta de sol estilo synthwave sobre el agua reflectante del mar, arte digital',
  'Dos torres futuristas con un puente aéreo cubierto de exuberante follaje, arte digital',
  'Una representación 3D de un globo aerostático con los colores del arco iris que vuela sobre un lago reflectante',
  'Una portada de cómic de un superhéroe con auriculares',
  'Una explosión centrada de polvo de colores sobre un fondo negro',
  'Una foto de un perro samoyedo con la lengua afuera abrazando a un gato siamés blanco',
  'Una foto de un monstruo de piel blanca parado en una habitación violeta',
  'Una foto de la escultura de Miguel Ángel de David con auriculares pinchando',
  'Un samurái montando un caballo en Marte, lomography.',
  'Un moderno y elegante Cadillac conduce a lo largo de la autopista Gardiner con el centro de Toronto al fondo, con un destello de lente, fotografía de 50 mm',
  'Una fotografía realista de una mujer joven con ojos azules y cabello rubio',
  'Un hombre parado frente a un portal estelar a otra dimensión',
  'Bob Esponja Pantalones Cuadrados en el Proyecto de la Bruja de Blair',
  'Un velociraptor trabajando en un puesto de perritos calientes, lomografía',
  'Un hombre que camina por las bulliciosas calles de Kowloon por la noche, iluminado por muchos letreros de tiendas de neón brillante, lente de 50 mm',
  'Una barbacoa que está viva, al estilo de una película de animación de Pixar',
  'Un club de baile cyborg futurista, luces de neón',
  'El anime japonés perdido de Star Wars 1990',
  'Una hamburguesa con forma de cubo de Rubik, fotografía profesional de alimentos',
  'Un erizo Synthwave, Blade Runner Cyberpunk',
  'Un astronauta que se encuentra con una forma de vida extraterrestre en un planeta distante, fotografía',
  'Un dinosaurio explorando Ciudad del Cabo, fotografía',
  'Un hombre que se enamora de su computadora, arte digital',
  'Una fotografía de un cyborg explorando Tokio de noche, lomography',
  'Drácula caminando por las calles de la ciudad de Nueva York en la década de 1920, fotografía en blanco y negro',
  'avión de onda sintética',
  'Un hombre deambula por las calles lluviosas de Tokio, con brillantes letreros de neón, 50 mm',
  'Un transbordador espacial sobrevolando Ciudad del Cabo, arte digital',
];
